spring.application.name=Laundry

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/laundry_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Thymeleaf
spring.thymeleaf.cache=false

# Custom error pages (no whitelabel)
server.error.whitelabel.enabled=false

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Telegram (okhttp)
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}

# telegram.bot.token
spring.config.import=optional:classpath:application-local.properties,optional:file:./application-local.properties

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.example.laundry=INFO
